# Generated by Django 4.0.3 on 2022-03-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymoudles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='havemoney',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='outmoney',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
