# Generated by Django 4.0.3 on 2022-03-02 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymoudles', '0003_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='outro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('valu', models.BigIntegerField()),
                ('date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outro_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
