# Generated by Django 4.0.3 on 2022-03-02 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymoudles', '0004_outro'),
    ]

    operations = [
        migrations.AddField(
            model_name='outro',
            name='fordebt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outro_debt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('allvalu', models.BigIntegerField()),
                ('mounthvalu', models.BigIntegerField()),
                ('finishtime', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
