# Generated by Django 4.0.3 on 2022-03-02 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymoudles', '0005_outro_fordebt_debt'),
    ]

    operations = [
        migrations.CreateModel(
            name='rootin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('allvalu', models.BigIntegerField()),
                ('number', models.IntegerField()),
                ('income', models.ManyToManyField(blank=True, null=True, related_name='income_outtro', to='mymoudles.income')),
                ('outro', models.ManyToManyField(blank=True, null=True, related_name='rootin_outtro', to='mymoudles.outro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rootin_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
