# Generated by Django 4.0.3 on 2022-03-02 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mymoudles', '0006_rootin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outro',
            name='fordebt',
        ),
    ]
