# Generated by Django 4.0.3 on 2022-03-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mymoudles', '0007_remove_outro_fordebt'),
    ]

    operations = [
        migrations.AddField(
            model_name='outro',
            name='fordebt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outro_debt', to='mymoudles.debt'),
        ),
    ]
